disl: NOT IN CFLOW OF foo() ch/usi/dag/disl/test/suite/cflow/app/TargetClass.main
disl: NOT IN CFLOW OF foo() ch/usi/dag/disl/test/suite/cflow/app/TargetClass.<init>
disl: IN CFLOW OF foo() ch/usi/dag/disl/test/suite/cflow/app/TargetClass.foo
app: TargetClass.foo() - begin
disl: IN CFLOW OF foo() ch/usi/dag/disl/test/suite/cflow/app/TargetClass.goo
app: TargetClass.goo()
app: TargetClass.foo() - end
disl: NOT IN CFLOW OF foo() ch/usi/dag/disl/test/suite/cflow/app/TargetClass.hoo
app: TargetClass.hoo() - begin
disl: NOT IN CFLOW OF foo() ch/usi/dag/disl/test/suite/cflow/app/TargetClass.goo
app: TargetClass.goo()
app: TargetClass.hoo() - end
