disl: <init> - this: ch.usi.dag.disl.test.suite.dynamicinfo.app.TargetClass
app: calling t.test(), which prints -2
disl: 1 - 3 = -2
app: -2
disl: before return, local a is 2
disl: test1 - this: ch.usi.dag.disl.test.suite.dynamicinfo.app.TargetClass
app: calling t.test2(true), which returns 1
disl: return with 1
disl: test2 - this: ch.usi.dag.disl.test.suite.dynamicinfo.app.TargetClass
app: calling t.test2(true), which returns -1
disl: return with -1
disl: test2 - this: ch.usi.dag.disl.test.suite.dynamicinfo.app.TargetClass
app: calling t.test3(1.0, 2)
app: d is now 2.0
app: i is now 1
disl: 2.0 - 1.0 = 1.0
app: 1.0
disl: before return, local d is 2.0
disl: before return, local i is 1
disl: test3 - this: ch.usi.dag.disl.test.suite.dynamicinfo.app.TargetClass
disl: main - this: null
