disl: Entering basic block. Is this a loopstart? false
disl: Entering basic block. Is this a loopstart? true
disl: Entering basic block. Is this a loopstart? false
app: 0
disl: Entering basic block. Is this a loopstart? true
disl: Entering basic block. Is this a loopstart? false
app: 1
disl: Entering basic block. Is this a loopstart? true
disl: Entering basic block. Is this a loopstart? false
app: 2
disl: Entering basic block. Is this a loopstart? true
disl: Entering basic block. Is this a loopstart? false
app: 3
disl: Entering basic block. Is this a loopstart? true
disl: Entering basic block. Is this a loopstart? false
