(In) Method main: 
Start
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.main
0
1
Ljava/lang/Object;
java.lang.String[]
--------------------
Receiver is null
This is null
OMG this is for the End
null
(Before) Method : 
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
null
(In) Method method1: 
Start
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
This is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Start
null
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method1
0
1
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is java.io.PrintStream
null
This is the body of TargetClass.method1
(Before) Method : 
processor for int
0
3
I
null
--------------------
processor for long
1
3
J
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Processor flag for the End
(In) Method method2: 
Start
processor for int
0
3
I
ch.usi.dag.disl.test.suite.processor.app.TargetClass
--------------------
processor for long
1
3
J
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
This is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Start
Processor flag for the End
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method2
0
1
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is java.io.PrintStream
Processor flag for the End
This is the body of TargetClass.method2
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.main
0
2
Ljava/lang/Object;
java.lang.String
--------------------
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.main
1
2
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Processor flag for the End
(In) Method method3: 
Start
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method3
0
2
Ljava/lang/Object;
java.lang.String
--------------------
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method3
1
2
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
This is ch.usi.dag.disl.test.suite.processor.app.TargetClass
OMG this is for the End
null
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method3
0
1
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is java.io.PrintStream
null
This is the body of TargetClass.method3
(Before) Method : 
processor for long
0
3
J
--------------------
processor for double
1
3
D
--------------------
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.main
2
3
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Processor flag for the End
(In) Method method3: 
Start
processor for long
0
3
J
--------------------
processor for double
1
3
D
--------------------
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method3
2
3
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
This is ch.usi.dag.disl.test.suite.processor.app.TargetClass
OMG this is for the End
null
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method3
0
1
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is java.io.PrintStream
null
This is the body of TargetClass.method3-1
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.main
0
2
Ljava/lang/Object;
java.lang.String[]
--------------------
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.main
1
2
Ljava/lang/Object;
int[]
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Processor flag for the End
(In) Method method4: 
Start
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method4
0
2
Ljava/lang/Object;
java.lang.String[]
--------------------
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method4
1
2
Ljava/lang/Object;
int[]
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
This is ch.usi.dag.disl.test.suite.processor.app.TargetClass
OMG this is for the End
null
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method4
0
1
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is java.io.PrintStream
null
This is the body of TargetClass.method4
(Before) Method : 
processor for int
0
3
Z
null
--------------------
processor for int
1
3
B
null
--------------------
processor for int
2
3
S
null
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Processor flag for the End
(In) Method method5: 
Start
processor for int
0
3
Z
ch.usi.dag.disl.test.suite.processor.app.TargetClass
--------------------
processor for int
1
3
B
ch.usi.dag.disl.test.suite.processor.app.TargetClass
--------------------
processor for int
2
3
S
ch.usi.dag.disl.test.suite.processor.app.TargetClass
--------------------
Receiver is ch.usi.dag.disl.test.suite.processor.app.TargetClass
This is ch.usi.dag.disl.test.suite.processor.app.TargetClass
Start
Processor flag for the End
(Before) Method : 
processor for object in method ch/usi/dag/disl/test/suite/processor/app/TargetClass.method5
0
1
Ljava/lang/Object;
java.lang.String
--------------------
Receiver is java.io.PrintStream
Processor flag for the End
This is the body of TargetClass.method5
(Before) Array : 
Testing dynamic context in processor
Accessed array index is 0
--------------------
(Before) Array : 
Testing dynamic context in processor
Accessed array index is 1
--------------------
