app: TargetClass.main(..) - .print(false)
disl: b enter bb index=0 size=2
disl: a enter bb
disl: a exit bb
disl: b exit bb
disl: b enter bb index=2 size=3
disl: a enter bb
disl: a exit bb
disl: a enter bb
app: TargetClass.print(..) - false
disl: a exit bb
disl: b exit bb
disl: b enter bb index=3 size=1
disl: a enter bb
disl: a exit bb
disl: b exit bb
app: TargetClass.main(..) - ~print(false)
app: TargetClass.main(..) - .print(true)
disl: b enter bb index=0 size=2
disl: a enter bb
disl: a exit bb
disl: b exit bb
disl: b enter bb index=1 size=4
disl: a enter bb
disl: a exit bb
disl: a enter bb
app: TargetClass.print(..) - true
disl: a exit bb
disl: a enter bb
disl: a exit bb
disl: b exit bb
disl: b enter bb index=3 size=1
disl: a enter bb
disl: a exit bb
disl: b exit bb
app: TargetClass.main(..) - ~print(true)
