/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_dag_disl_DiSL_CodeOption_Flag */

#ifndef _Included_ch_usi_dag_disl_DiSL_CodeOption_Flag
#define _Included_ch_usi_dag_disl_DiSL_CodeOption_Flag
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_usi_dag_disl_DiSL_CodeOption_Flag_CREATE_BYPASS
#define ch_usi_dag_disl_DiSL_CodeOption_Flag_CREATE_BYPASS 1L
#undef ch_usi_dag_disl_DiSL_CodeOption_Flag_DYNAMIC_BYPASS
#define ch_usi_dag_disl_DiSL_CodeOption_Flag_DYNAMIC_BYPASS 2L
#undef ch_usi_dag_disl_DiSL_CodeOption_Flag_SPLIT_METHODS
#define ch_usi_dag_disl_DiSL_CodeOption_Flag_SPLIT_METHODS 4L
#undef ch_usi_dag_disl_DiSL_CodeOption_Flag_CATCH_EXCEPTIONS
#define ch_usi_dag_disl_DiSL_CodeOption_Flag_CATCH_EXCEPTIONS 8L
#undef ch_usi_dag_disl_DiSL_CodeOption_Flag_GRAAL_SUPPORT
#define ch_usi_dag_disl_DiSL_CodeOption_Flag_GRAAL_SUPPORT 16L
#ifdef __cplusplus
}
#endif
#endif
