app: TargetClass.main - begin
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.<init> ()V
app: TargetClass.test_int
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_int (I)V
disl: 	arg[0]
disl: 		java.lang.Integer
disl: 		42
app: TargetClass.test_Integer
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_Integer (Ljava/lang/Integer;)V
disl: 	arg[0]
disl: 		java.lang.Integer
disl: 		42
app: TargetClass.test_float
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_float (F)V
disl: 	arg[0]
disl: 		java.lang.Float
disl: 		42.42
app: TargetClass.test_Float
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_Float (Ljava/lang/Float;)V
disl: 	arg[0]
disl: 		java.lang.Float
disl: 		42.42
app: TargetClass.test_double
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_double (D)V
disl: 	arg[0]
disl: 		java.lang.Double
disl: 		42.42
app: TargetClass.test_Double
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_Double (Ljava/lang/Double;)V
disl: 	arg[0]
disl: 		java.lang.Double
disl: 		42.42
app: TargetClass.test_String
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_String (Ljava/lang/String;)V
disl: 	arg[0]
disl: 		java.lang.String
disl: 		my test string
app: TargetClass.test_Object
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_Object (Ljava/lang/Object;)V
disl: 	arg[0]
disl: 		java.lang.String
disl: 		my test object string
app: TargetClass.test_ObjectArray
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_ObjectArray ([Ljava/lang/Object;)V
disl: 	arg[0]
disl: 			java.lang.String
disl: 			str1
disl: 			java.lang.String
disl: 			str2
disl: 			java.lang.String
disl: 			str3
app: TargetClass.test_MultipleObjectArray
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_MultipleObjectArray ([Ljava/lang/Object;[Ljava/lang/Object;)V
disl: 	arg[0]
disl: 			java.lang.String
disl: 			1str1
disl: 			java.lang.String
disl: 			1str2
disl: 			java.lang.String
disl: 			1str3
disl: 	arg[1]
disl: 			java.lang.String
disl: 			2str1
disl: 			java.lang.String
disl: 			2str2
disl: 			java.lang.String
disl: 			2str3
app: TargetClass.test_VaribleObjectArray
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.test_VariableObjectArray ([[Ljava/lang/Object;)V
disl: 	arg[0]
disl: 				java.lang.String
disl: 				1str1
disl: 				java.lang.String
disl: 				1str2
disl: 				java.lang.String
disl: 				1str3
disl: 				java.lang.String
disl: 				2str1
disl: 				java.lang.String
disl: 				2str2
disl: 				java.lang.String
disl: 				2str3
app: TargetClass.main - end
disl: args for ch/usi/dag/disl/test/suite/args/app/TargetClass.main ([Ljava/lang/String;)V
disl: 	arg[0]
